#!/bin/sh

if [ $# -eq 0 ]; then
    echo "usage : recp <file list>"
    exit 0
fi

os=`uname -s`

case $os in
Linux)
    cp="xclip -sel clip"
    ;;
Darwin)
    cp="pbcopy"
    ;;
*)
    echo "'$os' not support yet!"
    exit 1
    ;;
esac

count=0
for fn in $@
do
    case $fn in
    *.sh | *.py)
        comment="# $fn"
        ;;
    *.sql)
        comment="--- $fn"
        ;;      
    *.html | *.htm)
        comment="<!-- $fn -->"
        ;;        
    *)
        comment="// $fn"
        ;;
    esac

    echo "$comment"
    cat $fn
    ((count++))
    if [ $count -ne $# ]; then
        echo
    fi
done | $cp
